name: Release docker image

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          # Docker registry username
          username: ${{ secrets.DOCKER_USERNAME }}
          # Docker registry password
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2.7.0
        with:
          platforms: linux/arm64, linux/amd64
          push: true
          tags: urbitech/coding-standard:latest
